@url_dev=http://localhost:3333/api/v1

POST {{url_dev}}/shop/signup
Content-Type: application/json    
x-api-key:1111

{
    "name":"thong cao",
    "email":"hehehehe9",
    "password":"1111"
} 

###

GET {{url_dev}}/shop/login
Content-Type: application/json    
x-api-key:1111

{
    "name":"thongcao",
    "email":"hehehehe9",
    "password":"1111"
}      

###
POST {{url_dev}}/shop/refreshToken
Content-Type: application/json
x-api-key:1111
x-client-id:6652fe88b190ad9be52e0aee
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjUyZmU4OGIxOTBhZDliZTUyZTBhZWUiLCJlbWFpbCI6ImhlaGVoZWhlOSIsImlhdCI6MTcxNjcxNTQ2MiwiZXhwIjoxNzE2ODg4MjYyfQ.ElXQtAbbBK5OkRK7Nb_Sa4wM85ApKyrbUYJ7b-eir_VUMfqPe0mhIdYiNXw7Z3XbWKBoFQBgSQGTRzIfjhxRMzoGf8WYyQN-UgXzxbPdnusNUIAOmq1s7woK4pZx-mpWRXzm157PGwFpx9uweEIgGSrbfh6cdsFAfBGgiz9By5vAWp29AAP0yvdHBhMrxUrRv7wN31LWsitNaQ9c0-JQXy1XrG2Cf1g4JA_7NcOkEYbysertubo-aF7-M03VmRMPiN7nRv2PA_l0eRt_vgFqRGANOe2b-BZl_sPN0BxEjwkzTf5mwYB0NMcRBv-tBkkTySk6uQ06fxegmi1Ke2qUJg
   
{
    "refreshToken":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjUyZmU4OGIxOTBhZDliZTUyZTBhZWUiLCJlbWFpbCI6ImhlaGVoZWhlOSIsImlhdCI6MTcxNjcxNTQ2MiwiZXhwIjoxNzE3MzIwMjYyfQ.wXz9r0lhrEdnlBhSib9Q1lBMRVzawph4EwKLoFGZLcMIfREuRZl3CSd_kXYTux33jSHC_i2A0uFYzcXxGqGa45BSaRIHFDG-RDn4ZO_Kt_y6LbNtQmzMJKjQ6MmBY-QIKeXOyCqGgc4K2zKkeVUlNa57xReCXzcoplLU0EAqY9K-eAZENAjuOwgiS474BLBTQV0XecKez42CZbb8lVeiU9HndMIpww5VJAvx3cpJOHxVfAxsQ5VHgWEgvPbN9hfxZjoKHtql_9Sunv4yAsftyFaa0ZBhMeCUOtEa2o9bRYSClzg0UgHX3DwviL0Y8m578z4HD9DMUrKRlsI7CBb-Aw"
}


