@url_dev=http://localhost:3333/api/v1

# POST {{url_dev}}/shop/signup
# Content-Type: application/json    
# x-api-key:1111

# {
#     "name":"thong cao",
#     "email":"hehehehe9",
#     "password":"1111"
# }       

GET {{url_dev}}/shop/login
Content-Type: application/json    
x-api-key:1111

{
    "name":"thong cao",
    "email":"hehehehe9",
    "password":"1111"
}       

