@url_dev=http://localhost:3333/api/v1

POST {{url_dev}}/shop/signup
Content-Type: application/json    
x-api-key:1111

{
    "name":"thong cao",
    "email":"hehehehe9",
    "password":"1111"
} 

###

GET {{url_dev}}/shop/login
Content-Type: application/json    
x-api-key:1111  
 
{
    "name":"thongcao",
    "email":"hehehehe9",
    "password":"1111"
}      

###
POST {{url_dev}}/shop/refreshToken
Content-Type: application/json
x-api-key:1111
x-client-id:6652fe88b190ad9be52e0aee
x-rtoken-id:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjUyZmU4OGIxOTBhZDliZTUyZTBhZWUiLCJlbWFpbCI6ImhlaGVoZWhlOSIsImlhdCI6MTcxNjgzMDUxMSwiZXhwIjoxNzE3NDM1MzExfQ.fx2ojkqCG_4ttfqSb0y3Zy5KGC_sFSFizIR-_ywTXzKrVA0oF0CdDXwu5qPCG70YJ3sv2IHhEUF1jss8B4owKffaH3qcbMUhEC8tzECJ4fKkSCi8StKjRM7fuwWMEkpKOQR-hK5tai9Fb-JJTrHPz1rK1u2ojJ92iRhMdMU9spN7WoFe7bXdZRW-d-xnLD1B6vMPvSzZC21u8mibVprvls2ZEyHAmL0Qgh6SAgA5zfn6_TaJK0T9fmA_NbsYwUGYiAzXc5sAgF0f3-FjZyFM5n7irWgrn-e9SKfapVKfGGk9MQGNk5RO__jZXFi6Os51A0Kmgk3TJexP58u3KKPvdQ



