@url_dev=http://localhost:3333/api/v1

POST {{url_dev}}/product
Content-Type: application/json    
x-api-key:1111
x-client-id:6652fe88b190ad9be52e0aee
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjUyZmU4OGIxOTBhZDliZTUyZTBhZWUiLCJlbWFpbCI6ImhlaGVoZWhlOSIsImlhdCI6MTcxNjg5NTQ5MCwiZXhwIjoxNzE3MDY4MjkwfQ.k3NKjzpA5cs1Y28zvQOge3B1GCt0OeUVO1Beu3c7jA4wnNgwL7XAaqKCS2LRiNXNYQBrmu5pU_bChBRFiTngi8BI6lr8924wM6d3JpsC2-yw6a-xOrGxZaB6rlCwvuHkkd-fkr01luJ6t7EHR8XKlLCpg8E7fBv_jee50mx7DBbwP7-kJb7VOF2BeYe2Vk3-loH4SaZDUoCPr1QiTkCLrtQlSSIP232bFMHQ4I94FPOYV7-tGm1ciKM56fLa0gAx20Qf9eD6Twmos7CSAQlz0Z-EttLvwBA0vgqVUNH7HsXC8OYxLFw4i6HxdcYba_-0z3kAyPezqjz408Zy6ja7Zw

{
   "product_name":"tadaaa",
    "product_description":"High-quality denim jeans",
    "product_price":"50",
    "product_shop":"6652fe88b190ad9be52e0aee",
    "product_type":"Clothing",
    "product_thumb":"product_thumb",
    "product_quantity":"5",
    "product_attributes":{
        "brand":"Levi",
        "size":"L",
        "material":"coton"
    }
}
 