@url_dev=http://localhost:3333/api/v1

POST {{url_dev}}/product
Content-Type: application/json    
x-api-key:1111
x-client-id:6652fe88b190ad9be52e0aee
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjUyZmU4OGIxOTBhZDliZTUyZTBhZWUiLCJlbWFpbCI6ImhlaGVoZWhlOSIsImlhdCI6MTcxNjg5NjU4OCwiZXhwIjoxNzE3MDY5Mzg4fQ.jmlfx_jiivfT4QG4Vzk1tw_n2th8XlOI1q013Bq12aR0IqIfgh-63W1Od1i51HhbEujCXqWyFDm9Mb4CKoXtl0PcOloacjb5en1k8Z6ImuEkfNRB-HwgM_xJ_SVg_ezl0c-MrOlK6uiTWmLi4bxVeGmimn5-Q4XoLY6syuDFhAl7n6sI29pjr1fTJltajavbjFA0Z5bgY5KhpU6I6TOxFVJRswj5LujYOhlJ92YEwpp7MfvcvoW75YvXpgERqKltmFY8bNmIgNq_i8lfoI1VSAkBEBr4xHLYqFIUsis0J57kzVezfGHz9ugSpIFzOfLqJy6acEy6wzaXnhjT2BoebQ

{
   "product_name":"tadaaa heheh asfhiue",
    "product_description":"High-quality denim jeans",
    "product_price":"50",
    "product_shop":"6652fe88b190ad9be52e0aee",
    "product_type":"Clothing",
    "product_thumb":"product_thumb",
    "product_quantity":"5",
    "product_attributes":{
        "brand":"Levi",
        "size":"L",
        "material":"coton"
    }
}
 
###
GET {{url_dev}}/product/drafts/all
Content-Type: application/json    
x-api-key:1111
x-client-id:6652fe88b190ad9be52e0aee
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjUyZmU4OGIxOTBhZDliZTUyZTBhZWUiLCJlbWFpbCI6ImhlaGVoZWhlOSIsImlhdCI6MTcxNjg5NjU4OCwiZXhwIjoxNzE3MDY5Mzg4fQ.jmlfx_jiivfT4QG4Vzk1tw_n2th8XlOI1q013Bq12aR0IqIfgh-63W1Od1i51HhbEujCXqWyFDm9Mb4CKoXtl0PcOloacjb5en1k8Z6ImuEkfNRB-HwgM_xJ_SVg_ezl0c-MrOlK6uiTWmLi4bxVeGmimn5-Q4XoLY6syuDFhAl7n6sI29pjr1fTJltajavbjFA0Z5bgY5KhpU6I6TOxFVJRswj5LujYOhlJ92YEwpp7MfvcvoW75YvXpgERqKltmFY8bNmIgNq_i8lfoI1VSAkBEBr4xHLYqFIUsis0J57kzVezfGHz9ugSpIFzOfLqJy6acEy6wzaXnhjT2BoebQ
